using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace TheMakarik.Testing.FileSystem.AutoNaming;

/// <summary>
/// Contains information used by the name generator during automatic naming of files and directories.
/// </summary>
public sealed class NamingInfo
{
    /// <summary>
    /// File extension that is currently being generated (with leading dot or empty string for directories).
    /// </summary>
    public string Extension { get; set; } = string.Empty;

    /// <summary>
    /// Counter of how many items were already generated by this naming session.
    /// </summary>
    public int Count { get; set; }

    /// <summary>
    /// Full path to the root directory of the current test file system.
    /// </summary>
    public string RootFileSystemPath { get; set; } = string.Empty;

    /// <summary>
    /// List of all full paths of items added to the file system so far (used for counting by extension).
    /// </summary>
    public IList<string> RootFileSystemContent { get; } = new List<string>();

    /// <summary>
    /// Custom key-value storage that can be used by advanced / custom name generators.
    /// </summary>
    public IDictionary<object, object> Properties { get; set; } = new Dictionary<object, object>();

    /// <summary>
    /// Optional fixed random seed. When set, random-based generators become deterministic.
    /// </summary>
    public int? RandomSeed { get; set; }

    /// <summary>
    /// Returns number of already created items with the current extension.
    /// Returns 0 if <see cref="Extension"/> is empty (i.e. counting directories).
    /// </summary>
    public int GetExtensionCount()
    {
        return Extension == string.Empty
            ? 0
            : RootFileSystemContent.Count(path => Path.GetExtension(path) == Extension);
    }
}